### ISSUE TITLE
Issue executing the Project and Repository steps

### ISSUE THREAD

**Issue by ghost** [dylanhaskins/PowerPlatformCICD#24]
Getting the below error and found the cause:

----------------- powershell error output ---------------------------------
```
You have logged in. Now let us find all the subscriptions to which you have access...

Would you like to [C]reate a new Project or [S]elect and existing one (Default [S]): S
Before you can run Azure DevOps commands, you need to run the login command(az login if using AAD/MSA identity else az devops login if using PAT token) to setup credentials.  Please see https://aka.ms/azure-devops-cli-auth for more information.

DevOps Project
Select the Project you wish to use
[0] 0 -  [?] Help (default is "0"):

Enter the name for the Git Repository you wish to Create: MYPROJECTNAME
Creating Git Repo MYPROJECTNAME
--project must be specified. The value should be the ID or name of a team project. You can set a default value by running: az devops configure --defaults project=<ProjectName>.
--project must be specified. The value should be the ID or name of a team project. You can set a default value by running: az devops configure --defaults project=<ProjectName>.
Cloning Git Repo MYPROJECTNAME locally
If prompted for credentials, enter the same credentials you used for dev.azure.com
```
------------------------------------------------------------------------

Seems to be caused by the url "https://dev.azure.com/" been included in line 147,150 & 167 in the "Provision_Full.ps1".  the parameter $adoOrg already contains the full URL.

Finding and replacing: `--organization=https://dev.azure.com/$adoOrg` with `--organization=$adoOrg` fixed the errors.

By removing the "https://dev.azure.com/" everything executes correctly

**Comment by dylanhaskins** [comment]
Thanks Pierre, 

That would certainly solve the issue you were facing. $adoOrg does however request that you just enter the **Name** part of the URL and not the full URL, which would prevent this issue from occurring.

**_Enter the name of your Azure DevOps Organisation (https://dev.azure.com/Name)_**

We could possible put in an additional check that ensure that we actually connected to the Org properly before progressing the script, so I will look into that.

**Comment by ghost** [comment]
Yeah, I have realised that now :D

I was literally copying the full path :):)

PEBKAK error :):)

PS: The framework is awesome :)  Andrew Mee pointed the project out to me.

**Comment by dylanhaskins** [comment]
:) No problems. Glad you came right.
