### ISSUE TITLE
Failing to connect to CE for the Solution Export process

### ISSUE THREAD

**Issue by ghost** [dylanhaskins/PowerPlatformCICD#25]
Hi, 

Unfortunately I have encountered an error I cannot seem to get past.

I have tried three different accounts all with System Adminisstrator in my orgs:  1 Global admin with MFA, 1 Global Admin without MFA, 1 "normal" account without MFA but still with System Administrator in the Orgs.

This is the output of the PowerShell window:

		Installing Solution Management Tools...
		Module Microsoft.Xrm.Data.Powershell version 2.8.5 or higher Found
		Feeds used:
		  https://api.nuget.org/v3/index.json
		  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

		Installing package 'Microsoft.CrmSdk.CoreTools' to 'D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\Tools'.
		  CACHE https://api.nuget.org/v3/registration4-gz-semver2/microsoft.crmsdk.coretools/index.json

		Attempting to gather dependency information for package 'Microsoft.CrmSdk.CoreTools.9.1.0.38' with respect to project 'D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\Tools', targeting 'Any,Version=v0.0'
		Gathering dependency information took 17.13 ms
		Attempting to resolve dependencies for package 'Microsoft.CrmSdk.CoreTools.9.1.0.38' with DependencyBehavior 'Lowest'
		Resolving dependency information took 0 ms
		Resolving actions to install package 'Microsoft.CrmSdk.CoreTools.9.1.0.38'
		Resolved actions to install package 'Microsoft.CrmSdk.CoreTools.9.1.0.38'
		Retrieving package 'Microsoft.CrmSdk.CoreTools 9.1.0.38' from 'nuget.org'.
		Adding package 'Microsoft.CrmSdk.CoreTools.9.1.0.38' to folder 'D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\Tools'
		Added package 'Microsoft.CrmSdk.CoreTools.9.1.0.38' to folder 'D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\Tools'
		Successfully installed 'Microsoft.CrmSdk.CoreTools 9.1.0.38' to D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\Tools
		Executing nuget actions took 167.92 ms
		Module Microsoft.Xrm.DevOps.Data.Powershell version 1.3.0 or higher Found
		Establishing connection to https://ORGNAME.crm6.dynamics.com

		MaxRetryCount                       : 10
		RetryPauseTime                      : 00:00:05
		IsReady                             : False
		IsBatchOperationsAvailable          : False
		Authority                           :
		OAuthUserId                         :
		ActiveAuthenticationType            : Office365
		OrganizationServiceProxy            :
		OrganizationWebProxyClient          :
		CurrentAccessToken                  :
		LastCrmError                        : Invalid Login Information : An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail.
											  An unsecured or incorrectly secured fault was received from the other party. See the inner FaultException for the fault code and detail. => Authentication FailureUnable to Login to Dynamics CRM
											  Unable to Login to Dynamics CRMOrganizationWebProxyClient is null
											  OrganizationWebProxyClient is null
		LastCrmException                    : System.Exception: OrganizationWebProxyClient is null
		CrmConnectOrgUriActual              : https://ORGNAME.crm6.dynamics.com/XRMServices/2011/Organization.svc
		ConnectedOrgFriendlyName            :
		ConnectedOrgUniqueName              :
		ConnectedOrgPublishedEndpoints      : {[OrganizationService, https://ORGNAME.crm6.dynamics.com/XRMServices/2011/Organization.svc]}
		ConnectionLockObject                : System.Object
		ConnectedOrgVersion                 :
		ConnectedOrgId                      : 00000000-0000-0000-0000-000000000000
		DisableCrossThreadSafeties          : False
		CallerId                            : 00000000-0000-0000-0000-000000000000
		CallerAADObjectId                   :
		SessionTrackingId                   :
		ForceServerMetadataCacheConsistency : False
		SdkVersionProperty                  : 9.0.43.979
		TenantId                            : 00000000-0000-0000-0000-000000000000
		EnvironmentId                       :
		_sdkVersionProperty                 : 9.0.43.979

		Establishing connection to https://ORGNAME.crm6.dynamics.com
		Cleaning up Context Files...
		Updating Solution version for PowerPlatform
		Get-CrmRecordsByFetch : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\OneDrive\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.7\Microsoft.Xrm.Data.Powershell.psm1:3263 char:20
		+ ...  $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount ...
		+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch

		Found:  -  -
		Get-CrmRecordsByFetch : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\SolutionExport.ps1:67 char:15
		+ $PatchQuery = Get-CrmRecordsByFetch -conn $conn @"
		+               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch

		Exporting Unmanaged Solution for PowerPlatform
		Get-CrmRecordsByFetch : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\OneDrive\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.7\Microsoft.Xrm.Data.Powershell.psm1:3263 char:20
		+ ...  $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount ...
		+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch

		Export-CrmSolution : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\SolutionExport.ps1:102 char:1
		+ Export-CrmSolution -SolutionName $global:SolutionName -SolutionZipFil ...
		+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-CrmSolution

		Exporting Managed Solution for PowerPlatform
		Get-CrmRecordsByFetch : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\OneDrive\Documents\WindowsPowerShell\Modules\Microsoft.Xrm.Data.Powershell\2.8.7\Microsoft.Xrm.Data.Powershell.psm1:3263 char:20
		+ ...  $results = Get-CrmRecordsByFetch -conn $conn -Fetch $fetch -TopCount ...
		+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-CrmRecordsByFetch

		Export-CrmSolution : System.Management.Automation.RuntimeException: Crm Service not initialized
		Crm Service not initialized
		At D:\Dev\Repos\PowerPlatform\Solutions\Scripts\Manual\SolutionExport.ps1:109 char:1
		+ Export-CrmSolution -SolutionName $global:SolutionName -Managed -Solut ...
		+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
			+ CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
			+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Export-CrmSolution

		Unpacking Solution PowerPlatform
		SolutionPackger CRM Solution Packaging Tool [Version 9.1.0.41]
		c 2017 Microsoft Corporation.  All rights reserved

		Read-only files will be over-written or deleted.
		Assumed Managed solution file not found: PowerPlatform_managed.zip
		SolutionPackager: Exception thrown: System.IO.FileNotFoundException: Assumed Managed solution file not found: PowerPlatform_managed.zip
		   at Microsoft.Crm.Tools.SolutionPackager.SolutionPackager.Run()
		   at Microsoft.Crm.Tools.SolutionPackager.Program.Main(String[] args), returning error code '1'

Is there something I am missing or misunderstanding?

Thanks in advance

**Comment by eugenevanstaden** [comment]
Can we close this issue?

**Comment by ghost** [comment]
The accounts I use are able to retrieve the orgs, connect to the orgs and create the Publisher and Solution, but cannot export the solution.

What is causing the issue?  It is failing every time stating the CRM Service is not initialised

I tried manually running the individual lines within PowerShell and they worked

**Comment by eugenevanstaden** [comment]
I've not seen this yet, will try and run a few tests to see if we can resolve.
@dylanhaskins  - any ideas?

**Comment by ghost** [comment]
I found the issue, I have been running through the code manually and found that this on line 36 of \Solutions\Scripts\Manual\SolutionExport.ps1 is where it fails:

![image](https://user-images.githubusercontent.com/13442622/75209821-6a381e00-57d3-11ea-9548-1dedc6c2fc03.png)

It seems that because Connect-CrmOnlineDiscovery is using OAuth whereas Connect-CrmOnline is using Office365 and thus failing... at least for my environments.

**Comment by eugenevanstaden** [comment]
Hi Pierre

you can replace with 
$conn = Connect-CrmOnlineDiscovery - Interactive

But this then negates the need then to read the config values created as part of the setup. We using this in environments with MFA and without MFA but unable to replicate.

Are you having this issue in the Provisioning also?

**Comment by ghost** [comment]
Replacing it caused failures in the deployment I commented it out and now am getting errors with the Template deployment to Azure. :(

Its all good, that is a whole other issue.

Thanks for the help
