### ISSUE TITLE
Cannot pick existing solution when more than 10 options

### ISSUE THREAD

**Issue by CoreySutton** [dylanhaskins/PowerPlatformCICD#6]
When there are more than 10 solution to pick from, you are only able to pick options 1-9. Options 10+ cannot be selected.

`PromptForChoice` uses the first character of the choice string as the selector. The strings are in the format `(<index>) - <solutionName>`. Therefore options 1-9 will have selectors 1 through 9. 
- Option 10 will have the selector `1` (**1**0) - MySolution
- Option 11 will have the selector `1` (**1**1) - MySolution1
- Option 20 will have the selector `2` (**2**0) - MySolution2

![image](https://user-images.githubusercontent.com/5017826/73321570-c167d300-42a7-11ea-8455-050225afe553.png)

Not sure the best way to fix this, but some blogs suggest paging the results to 10 options at a time

**Comment by dylanhaskins** [comment]
Thanks @CoreySutton, your update works like a charm. Pull request has been completed :)
